/**
 *
 * $Id$
 */
package container.validation;

import container.Container;
import container.Stack;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link container.ContainerModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContainerModelValidator {
   boolean validate();

   boolean validateStack(EList<Stack> value);
   boolean validateNextContainer(Container value);
   boolean validateContainer(EList<Container> value);
}
